# Generated by Django 3.1 on 2020-08-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200828_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_extended',
            name='access_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'basic'), (2, 'Intermediate'), (3, 'Admin')], default=1),
        ),
    ]
