# Generated by Django 3.1 on 2020-08-31 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200829_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_extended',
            old_name='User',
            new_name='user',
        ),
    ]
