# Generated by Django 3.1 on 2020-08-29 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_Wholeseller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('mode_of_payment', models.PositiveSmallIntegerField(choices=[(1, 'Cash'), (2, 'Credit')], default=1)),
            ],
        ),
    ]
