# Generated by Django 3.1 on 2020-08-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party_wholeseller',
            name='dl_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='party_wholeseller',
            name='pan_number',
            field=models.CharField(max_length=11),
        ),
    ]
