# Generated by Django 3.1 on 2020-09-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_auto_20200829_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party_wholeseller',
            name='pan_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
