# Generated by Django 3.1 on 2020-08-29 08:32

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_name', models.CharField(max_length=20)),
                ('comp_address', models.CharField(max_length=50)),
                ('comp_GST', models.IntegerField()),
                ('contact', phone_field.models.PhoneField(blank=True, help_text='Company_Number', max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('purchase_rate', models.FloatField()),
                ('purchase_sgst', models.FloatField()),
                ('scheduled_drug', models.BooleanField(default=False)),
                ('unit_of_packing', models.IntegerField()),
                ('sale_rate', models.FloatField()),
                ('sale_sgst', models.FloatField()),
                ('free', models.IntegerField()),
                ('mrp', models.FloatField()),
                ('expiry_date', models.DateField()),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.comp')),
            ],
        ),
    ]
