# Generated by Django 3.1 on 2020-09-01 19:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party', '0003_auto_20200901_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=20)),
                ('comp_address', models.CharField(max_length=50)),
                ('comp_GST', models.PositiveIntegerField()),
                ('contact', phone_field.models.PhoneField(blank=True, help_text='Company_Number', max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('purchase_rate', models.FloatField(null=True)),
                ('purchase_sgst', models.FloatField(null=True)),
                ('scheduled_drug', models.BooleanField(default=False)),
                ('unit_of_packing', models.CharField(max_length=15)),
                ('sale_rate', models.FloatField(null=True)),
                ('sale_sgst', models.FloatField(null=True)),
                ('free', models.IntegerField(null=True)),
                ('mrp', models.FloatField()),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('party_wholeseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.party_wholeseller')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=10)),
                ('expiry', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField()),
                ('product_id', models.OneToOneField(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='company.product')),
            ],
        ),
    ]
