# Generated by Django 3.1 on 2020-09-01 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='party_wholeseller_id',
            new_name='party_wholeseller',
        ),
    ]
