# Generated by Django 3.1 on 2020-08-29 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200829_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiry_date',
        ),
        migrations.AlterField(
            model_name='company',
            name='comp_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.IntegerField()),
                ('expiry', models.DateField(default=django.utils.timezone.now)),
                ('product_id', models.OneToOneField(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='company.product')),
            ],
        ),
    ]
