# Generated by Django 3.1 on 2020-08-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20200829_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
