# Generated by Django 3.1 on 2020-08-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_batch_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
