# Generated by Django 3.1 on 2020-08-29 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_auto_20200829_2251'),
        ('company', '0007_auto_20200830_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='party_wholeseller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.party_wholeseller'),
        ),
    ]
