# Generated by Django 3.1 on 2020-08-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20200830_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='free',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_sgst',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_sgst',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_packing',
            field=models.CharField(max_length=15),
        ),
    ]
